language: c
sudo: false

env:
  global:
    # ctanupload uses these
    - CONTRIBUTION=skmath
    - NAME="Simon Sigurdhsson"
    - EMAIL="Sigurdhsson@gmail.com"
    - DIRECTORY=/macros/latex/contrib/skmath
    - SUMMARY="Extensions to the maths command repertoir"
    - LICENSE=free
    - FREEVERSION=lppl

before_install:
  - mkdir -p $HOME/texlive && curl -L https://github.com/urdh/texlive-blob/releases/download/20190725/texlive.tar.xz | tar -JxC $HOME/texlive

install:
  - PATH=$HOME/texlive/bin/x86_64-linux:$PATH
  - tlmgr update --self --all
  - tlmgr install paratype
  - tlmgr install opensans
  - tlmgr install sourcecodepro
  - tlmgr install ly1
  - tlmgr install xindy
  - tlmgr install mweights
  - tlmgr install isomath
  - tlmgr remove --force skmath || true

script:
  - make dist
  - make test

after_success:
  - ./deploy-ctan.sh skmath.tar.gz

deploy:
  provider: releases
  api_key:
    secure: F+x6zV1wGUKu/R+vduT4zQJB4D66zsZB9wnKrVsYmS+l/huDBAhe6SB6XAlNUeqoHD0CdrKjfw135ittS5LVyIuvyGZ7QuT6h4qlfb7zPCOWwrrQd0rZUkJ3CqMUD9Oain3pTSqAiO/Qh6WA8HXGFHeCuKSTEwfJF0KxeCsyqw0=
  file: skmath.tar.gz
  skip_cleanup: true
  on:
    repo: urdh/skmath
    tags: true
