language: c
sudo: false

env:
  global:
    # ctanupload uses these
    - CONTRIBUTION=skmath
    - NAME="Simon Sigurdhsson"
    - EMAIL="Sigurdhsson@gmail.com"
    - DIRECTORY=/macros/latex/contrib/skmath
    - LICENSE=free
    - FREEVERSION=lppl

before_install:
  - mkdir -p $HOME/texlive && curl -L https://github.com/urdh/texlive-blob/releases/download/20160619/texlive.tar.xz | tar -JxC $HOME/texlive

install:
  - PATH=$HOME/texlive/bin/x86_64-linux:$PATH
  - tlmgr update --self --all
  - tlmgr install paratype
  - tlmgr install opensans
  - tlmgr install sourcecodepro
  - tlmgr install ly1
  - tlmgr install xindy

script:
  - make dist
  - make test

after_success:
  - ./deploy-ctan.sh skmath.tar.gz

deploy:
  provider: releases
  api_key:
    secure: ceQqgJfEN2V4A1Eqd61zBEZ/Dt2L/3jMQtKuU6lgJSJiwUd6igE19HPegGwDSUr48amrms6yoJoTLX5GfeeiNkcvGbregQL92ZiTakIn4NL2s2whBYXRswSMQxOU+mUQz2ugHB3h3PorWmiPcM7W8CrLfcUMBNeProBWLcovOGo=
  file: skmath.tar.gz
  skip_cleanup: true
  on:
    repo: urdh/skmath
    tags: true
